[tool.poetry]
name = "test2"
version = "0.1.0"
description = ""
authors = ["Gabriel Borba"]

[tool.poetry.dependencies]
python = ">=3.10"

[tool.poetry.dev-dependencies]
autopep8 = ">=1.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
